sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - sudo apt-get install ghostscript
    - sudo apt-get install p7zip p7zip-full
    - 7z x 0x04/task3/web_log.tsv.7z
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    - ls 0x04/task1/img

script:
  - bash 0x04/task1/task1.sh -d 0x04/task1/img -h
  - bash 0x04/task1/task1.sh -d 0x04/task1/img -r
  - bash 0x04/task1/task1.sh -d 0x04/task1/img -w "shielding"
  - bash 0x04/task1/task1.sh -d 0x04/task1/img -s "new"
  - bash 0x04/task2/task2.sh -h
  - bash 0x04/task2/task2.sh -c
  - bash 0x04/task3/task3.sh -h -1 -2 -3 -4 -5 -6 news.ti.com
  

after_script: 
  - ls 0x04/task1/img
  - /usr/bin/shellcheck 0x04/task1/task1.sh
  - /usr/bin/shellcheck 0x04/task2/task2.sh
  - /usr/bin/shellcheck 0x04/task3/task3.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
