sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version

script:
  - bash 0x04/task1/task1.sh -d 0x04/task1/img -h
  - bash 0x04/task1/task1.sh -d 0x04/task1/img -r
  - bash 0x04/task1/task1.sh -d 0x04/task1/img -w "shielding"
  - bash 0x04/task1/task1.sh -d 0x04/task1/img -s "new"

after_script: 
  - /usr/bin/shellcheck 0x04/task1/task1.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
